<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
                xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
                exclude-result-prefixes="s">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  
  <xsl:template match="/">
    <html>
      <head>
        <title>PrimeMetric XML Sitemap</title>
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            background-color: #f0f4f8;
            color: #333;
            margin: 0;
            padding: 2rem;
          }
          #content {
            max-width: 900px;
            margin: 0 auto;
            background: #fff;
            padding: 2rem;
            border-radius: 1rem;
            box-shadow: 0 10px 30px -15px rgba(0,0,0,0.1);
          }
          h1 {
            color: #2c3e50;
            font-size: 2rem;
            margin-bottom: 0.5rem;
          }
          p {
            color: #7f8c8d;
            font-size: 1rem;
            margin-top: 0;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 2rem;
          }
          th, td {
            text-align: left;
            padding: 0.75rem 1rem;
            border-bottom: 1px solid #ecf0f1;
          }
          th {
            background-color: #ecf0f1;
            color: #7f8c8d;
            font-size: 0.85rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
          }
          tr:hover td {
            background-color: #f7f9fa;
          }
          a {
            color: #3498db;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          .footer {
            margin-top: 2rem;
            text-align: center;
            font-size: 0.9rem;
            color: #95a5a6;
          }
        </style>
      </head>
      <body>
        <div id="content">
          <h1>PrimeMetric XML Sitemap</h1>
          <p>
            This sitemap contains <xsl:value-of select="count(s:urlset/s:url)"/> URLs and was generated to help search engines index our content.
          </p>
          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th>Last Modified</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="s:urlset/s:url">
                <tr>
                  <td>
                    <xsl:variable name="loc" select="s:loc"/>
                    <a href="{$loc}"><xsl:value-of select="s:loc"/></a>
                  </td>
                  <td>
                    <xsl:value-of select="substring(s:lastmod,1,10)"/>
                  </td>
                  <td>
                    <xsl:value-of select="s:priority"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
          <div class="footer">
            Generated by PrimeMetric
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>