'use client';

import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import CalculatorLayout from "@/components/CalculatorLayout";
import CalculatorContentSection from "@/components/CalculatorContentSection";
import { useToast } from "@/hooks/use-toast";

const RandomNumberGenerator = () => {
  const [min, setMin] = useState("1");
  const [max, setMax] = useState("100");
  const [result, setResult] = useState<number | null>(null);
  const { toast } = useToast();

  const generate = () => {
    const minVal = parseInt(min);
    const maxVal = parseInt(max);
    if (isNaN(minVal) || isNaN(maxVal) || minVal > maxVal) {
      toast({
        variant: "destructive",
        title: "Invalid Input",
        description: "Please enter a valid range where min is not greater than max.",
      });
      return;
    }
    const randomNumber = Math.floor(Math.random() * (maxVal - minVal + 1)) + minVal;
    setResult(randomNumber);
    toast({
        title: "Number Generated!",
        description: `Your random number is ${randomNumber}.`,
    });
  };

  return (
    <CalculatorLayout
      title="Random Number Generator"
      description="Generate a random integer within a specified range."
      canonicalUrl="/math-calculators/random-number-generator"
    >
      <Card className="p-6">
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label>Minimum Value</Label>
              <Input type="number" value={min} onChange={(e) => setMin(e.target.value)} placeholder="e.g., 1" />
            </div>
            <div>
              <Label>Maximum Value</Label>
              <Input type="number" value={max} onChange={(e) => setMax(e.target.value)} placeholder="e.g., 100" />
            </div>
          </div>
          <Button onClick={generate} className="w-full gradient-button">Generate Number</Button>
          {result !== null && (
            <div className="mt-6 p-4 bg-primary/10 rounded-lg text-center">
              <p className="text-sm text-muted-foreground">Your Random Number</p>
              <p className="text-5xl font-bold text-primary">{result}</p>
            </div>
          )}
        </div>
      </Card>
      
       <CalculatorContentSection
        aboutContent="The Random Number Generator creates a random integer within a specified range (inclusive). This tool is useful for a wide variety of applications, from games and contests to statistical sampling and cryptography."
        useCases={[
            { title: "Games and Contests", description: "Use it to pick a random winner from a numbered list of participants, or for any game that requires a random number." },
            { title: "Decision Making", description: "Can't decide? Assign numbers to your options and let the generator choose for you." },
            { title: "Statistical Sampling", description: "Randomly select samples from a dataset for statistical analysis." },
        ]}
        tips={[
            { title: "Inclusive Range", description: "The generator includes both the minimum and maximum values in the possible outcomes." },
            { title: "Integer Output", description: "This tool generates whole numbers (integers). It does not produce decimal numbers." },
            { title: "Pseudo-Random", description: "Like all computer-based random number generators, the numbers are 'pseudo-random.' They are generated by an algorithm and are not truly random in a physical sense, but they are random enough for most everyday purposes." },
        ]}
        faqs={[
            { question: "How does the random number generator work?", answer: "It uses JavaScript's Math.random() function, which generates a floating-point, pseudo-random number in the range [0, 1). The calculator then scales this number to fit your specified min/max range and rounds it to the nearest integer." },
            { question: "Are the numbers truly random?", answer: "Computer-generated numbers are technically pseudo-random, meaning they are produced by a deterministic algorithm. However, for all practical purposes like games, contests, and decision-making, they are sufficiently random." },
            { question: "Can I generate more than one number at a time?", answer: "This basic version generates one number per click. To generate a list of random numbers, you would click the 'Generate' button multiple times." },
        ]}
      />
    </CalculatorLayout>
  );
};

export default RandomNumberGenerator;

    