
import LegalPageLayout from "@/components/LegalPageLayout";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Terms of Service | Prime Metric",
    description: "Read the Terms of Service for Prime Metric before using our calculators and tools.",
    keywords: "terms of service, terms and conditions, primemetric terms, user agreement",
    alternates: {
        canonical: "https://primemetric.online/terms-of-service",
    }
};

const TermsOfServicePage = () => {
  return (
    <LegalPageLayout title="Terms & Conditions">
        <p className="text-muted-foreground mb-6 text-center">Last updated: November 24, 2025</p>
        
        <div className="space-y-8 text-muted-foreground">
          <p>
            Welcome to Prime Metric. These Terms and Conditions (“Terms”, “Agreement”) govern your access to and use of the website located at https://primemetric.online, including all calculators, tools, templates, dashboards, services, and features available through the site (“Services”).
          </p>
          <p>
            By accessing or using Prime Metric, you agree to be bound by these Terms. If you do not agree, you must discontinue use immediately. These Terms apply to all visitors, users, account holders, and anyone who interacts with the website.
          </p>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">1. Acceptance of Terms</h2>
            <p>By accessing PrimeMetric or using any of our Services, you:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Agree to comply with these Terms</li>
                <li>Confirm you are at least 13 years old</li>
                <li>Accept our Privacy Policy and Cookie Policy</li>
                <li>Agree not to misuse the platform</li>
                <li>Understand that our calculations are for educational and informational purposes only</li>
            </ul>
            <p className="mt-2">If you create an account or use our invoice generator, calculator tools, or downloadable resources, these Terms fully apply.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">2. About Prime Metric</h2>
            <p>Prime Metric is an online platform providing:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>100+ calculators and tools</li>
                <li>Educational breakdowns</li>
                <li>Steps, formulas, and examples</li>
                <li>Invoice generator templates</li>
                <li>Saving invoice history</li>
                <li>Informational guides</li>
            </ul>
            <p className="mt-2">Prime Metric does not provide certified financial, legal, health, tax, or medical advice. All results generated by our tools should be interpreted responsibly.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">3. User Accounts</h2>
            <p>Some features (e.g., invoice saving, dashboard access) require creating an account. When registering:</p>
             <p className="font-semibold mt-2">You must:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Provide accurate information</li>
                <li>Not use another person’s identity</li>
                <li>Not create multiple accounts to misuse services</li>
                <li>Keep your login credentials secure</li>
            </ul>
            <p className="font-semibold mt-2">You agree that:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>You are responsible for all activities under your account</li>
                <li>We may suspend accounts for misuse</li>
                <li>We may delete inactive or duplicate accounts</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">4. Use of Our Services</h2>
            <p>By using Prime Metric, you agree:</p>
            <p className="font-semibold mt-2">✔ You WILL:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Use tools only for legal purposes</li>
                <li>Follow all instructions and limitations</li>
                <li>Respect our intellectual property</li>
                <li>Use correct information in calculators (where required)</li>
            </ul>
            <p className="font-semibold mt-2">❌ You WILL NOT:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Reverse engineer the site</li>
                <li>Attempt to hack, disable, or overload servers</li>
                <li>Post harmful, illegal, malicious content</li>
                <li>Automate scraping or mass extraction of data</li>
                <li>Clone or republish our content without permission</li>
                <li>Use bots or automated tools to generate fake invoices or traffic</li>
            </ul>
            <p className="mt-2">Unauthorized usage may lead to account termination.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">5. Educational Content Disclaimer</h2>
            <p>All calculators and tools on PrimeMetric provide:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Estimates</li>
                <li>Suggested values</li>
                <li>Informational insights</li>
                <li>Step-by-step explanations</li>
            </ul>
            <p className="font-semibold mt-2">However:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>They are NOT a replacement for professional advice.</li>
                <li>They should NOT be used for financial, legal, tax, investment, medical, or professional decision-making without expert consultation.</li>
            </ul>
            <p className="mt-2">Prime Metric is not responsible for losses resulting from incorrect usage, interpretation, or reliance on calculated values.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">6. Accuracy of Information</h2>
            <p>We regularly review and update our tools, formulas, and educational content. However:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>We do not guarantee 100% accuracy</li>
                <li>Mathematical or formula errors may occasionally occur</li>
                <li>External factors may influence real-world results</li>
                <li>Users are responsible for verifying results before action</li>
            </ul>
            <p className="mt-2">We disclaim liability for damages caused by calculation inaccuracies.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">7. Intellectual Property Rights</h2>
            <p>All content on Prime Metric, including:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Calculator logic</li>
                <li>Educational content</li>
                <li>Designs</li>
                <li>Templates</li>
                <li>UI/UX assets</li>
                <li>Text descriptions</li>
                <li>Graphical elements</li>
                <li>Branding</li>
                <li>Logos</li>
            </ul>
            <p className="mt-2">is the exclusive property of Prime Metric.</p>
            <p className="font-semibold mt-2">Users MAY NOT:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Copy or republish tools</li>
                <li>Use our design system commercially</li>
                <li>Redistribute or resell calculators</li>
                <li>Use our educational content elsewhere</li>
                <li>Download or extract source code</li>
                <li>Claim authorship of our tools</li>
                <li>Create competing services using our content</li>
            </ul>
            <p className="mt-2">Doing so violates copyright laws.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">8. Third-Party Services</h2>
            <p>Prime Metric may integrate with third-party tools like:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Google Analytics</li>
                <li>Google AdSense</li>
                <li>Firebase</li>
                <li>Social platforms</li>
            </ul>
            <p className="mt-2">These third parties may collect anonymized data. Prime Metric is not responsible for:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Third-party accuracy</li>
                <li>Their policies</li>
                <li>Data handling practices</li>
            </ul>
            <p className="mt-2">Users should review their privacy policies for details.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">9. Advertising and Monetization</h2>
            <p>Prime Metric uses:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Google AdSense</li>
                <li>Display ads</li>
                <li>Affiliate links (in the future)</li>
            </ul>
            <p className="mt-2">Ads shown on the site:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Are controlled by external providers</li>
                <li>Do not represent our endorsement</li>
                <li>May be targeted based on browsing behavior</li>
            </ul>
            <p className="mt-2">We follow Google Publisher Policies strictly.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">10. User Content</h2>
            <p>Some tools allow uploading content, such as:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Logos for invoices</li>
                <li>Text descriptions</li>
                <li>Business information</li>
            </ul>
            <p className="mt-2">By uploading content, you confirm:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>You own the rights to the content</li>
                <li>It does not infringe third-party rights</li>
                <li>It is not harmful, illegal, or offensive</li>
                <li>It does not violate copyright law</li>
            </ul>
            <p className="mt-2">We reserve the right to delete inappropriate content.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">11. Invoice Generator Terms</h2>
            <p>The invoice generator feature includes:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Pre-built templates</li>
                <li>Logo upload</li>
                <li>PDF/PNG downloads</li>
                <li>Save invoice history</li>
            </ul>
            <p className="mt-2">You agree that:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Templates are for personal/business use only</li>
                <li>You will not misuse them for fraud</li>
                <li>You are responsible for legal compliance of created invoices</li>
                <li>We do not verify authenticity of invoice entries</li>
            </ul>
            <p className="mt-2">Prime Metric is not responsible for:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Business losses</li>
                <li>Tax disputes</li>
                <li>False invoices created by users</li>
                <li>Data loss due to user error</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">12. Limitation of Liability</h2>
            <p>To the maximum extent allowed by law: Prime Metric is NOT liable for:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Loss of data</li>
                <li>Financial loss</li>
                <li>Business damage</li>
                <li>Incorrect calculation results</li>
                <li>Billing disputes</li>
                <li>Health or fitness decisions</li>
                <li>Damages caused by user negligence</li>
                <li>Losses based on reliance on calculators</li>
            </ul>
            <p className="mt-2">Our tools are educational only.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">13. Termination & Suspension</h2>
            <p>We may suspend or terminate accounts if:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>You violate Terms</li>
                <li>You misuse tools</li>
                <li>You attempt to exploit system vulnerabilities</li>
                <li>You create fraudulent invoices</li>
                <li>You spam or abuse support</li>
            </ul>
            <p className="mt-2">We may also restrict or modify features at any time.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">14. Modifications to Services</h2>
            <p>We reserve the right to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Update tools</li>
                <li>Add new calculators</li>
                <li>Remove outdated features</li>
                <li>Improve UI/UX</li>
                <li>Limit access for maintenance</li>
            </ul>
            <p className="mt-2">We are not liable for downtime or temporary unavailability.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">15. Governing Law</h2>
            <p>These Terms are governed by the laws of your country or region unless otherwise specified. All disputes should be resolved through local applicable laws.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">16. Changes to Terms</h2>
            <p>We may update these Terms periodically. Continued use after changes indicates acceptance of updated Terms.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-foreground">17. Contact Us</h2>
            <p>
              If you have any questions regarding these Terms:
              <br/>
              📧 <a href="mailto:help@primemetric.online" className="text-primary hover:underline">help@primemetric.online</a>
            </p>
            <p className="mt-2">We aim to respond promptly to all genuine queries.</p>
          </section>
        </div>
    </LegalPageLayout>
  );
};

export default TermsOfServicePage;
